# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 142af0c8f15433ed1ebafe1c47836936116319e14e6130a786ba87b72651cadbe4c4250226d235b238e438fdc233667ab15350922a533b1fe88b7a64c301b407

test:
  secret_key_base: 386367c1295e2c695e75847bff321b81c9718b13d39eb91da648967de6a2e386aaf91cdee15a0e061cf338df83dfeb58ec5d74b2e099d0a9f317575912df0b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
